[package]
name = "databus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "databus"
crate-type = ["cdylib"]

[dependencies]
databus_core = { path = "../databus-core" }

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]