# List the start-up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: packaging/.gitpod.Dockerfile

tasks:
  - name: install dependency
    init: |
      make install
    command: |
      echo "Happy Coding"
#  - name: build APITable
#    command: |
#      make build

  - name: dataenv APITable
    command: |
      make dataenv

  - name: run APITable
    command: |
      make run-dev-all

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: open-preview
