# List the start-up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: packaging/.gitpod.Dockerfile

tasks:
  - name: install dependency
    init: |
      make install
    command: |
      echo "Happy Coding"

  - name: dataenv APITable
    command: |
      make dataenv

  - name: run APITable1
    command: |
      make _run-local-backend-server

  - name: run APITable2
    command: |
      make _run-local-room-server

  - name: run APITable3
    command: |
      make _run-local-web-server

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
