version: '3'

services:
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  redis:
    ports:
      - "6379:6379"

  mysql:
    ports:
      - "3306:3306"

  rabbitmq:
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"

  databus-server:
    ports:
      - "8625:8625"
    environment:
      - BACKEND_BASE_URL=http://host.docker.internal:8081/api/v1/
    extra_hosts:
      - host.docker.internal:host-gateway
