[tool.poetry]
name = "databus"
version = "0.1.0"
description = "DataBus - the data abstraction and processing layer for APITable"
authors = ["Your Name <you@example.com>"]
license = "AGPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
maturin = "^1.1.0"


[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
